version: '3.8'

services:
  music-store-db-svc.music-store.svc.cluster.local:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Todor123!"
      ACCEPT_EULA: "Y"
    container_name: music-store-db-svc.music-store.svc.cluster.local
    ports:
      - "1433:1433"

  music-store-app:
    image: tosh3/kiii-music-store-app
    container_name: music-store-app
    ports:
      - "8081:8080"
    depends_on:
      - music-store-db-svc.music-store.svc.cluster.local
    environment:
      ASPNETCORE_ENVIRONMENT: Development